GongchaOfficial/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GongchaOfficial.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Location()
        {
            return View();
        }
    }
}

GongchaOfficial/Controllers/WomenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GongchaOfficial.Models;

namespace GongchaOfficial.Controllers
{
    public class WomenController : Controller
    {
        dbGongchaDataContext data = new dbGongchaDataContext();

        // GET: Women
        private List<Product> getNewProDuctWithSex(int count)
        {
            return data.Products.Where(s => s.SexId == "women" || s.SexId == "unisex").OrderByDescending(a => a.ProductReleaseDate).Take(count).ToList();
        }
        private List<Product> getProductWithId(String id)
        {
            return data.Products.Where(s => s.CategoryId == id).ToList();
        } 
        public ActionResult Index(String id)
        {
            if (id == null)
            {
                var product = getNewProDuctWithSex(20);
                return View(product);
            }
            else
            {
                var product = data.Products.Where(s => s.CategoryId == id).ToList();
                return View(product);
            }
        }

        //Load Category to left list
        public ActionResult Category()
        {
            var listcategory = from ct in data.Categories.Where(a => a.SexId == "women" || a.SexId =="unisex") select ct;
            return PartialView(listcategory);
        }

        public ActionResult ProductDetail(string id)
        {
            var product = from pd in data.Products
                          where pd.ProductId == id
                          select pd;

            return View(product.Single());
        }

    }
}

GongchaOfficial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @*Test*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GongchaOfficial/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet" />


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("TRANG CHỦ", "Index", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("QUẢN LÝ SẢN PHẨM", "Product", "Admin")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div>
            @RenderBody()
        </div>

    </div>
    </div>
    </div>
    <!-- /.container -->
    
    <!-- /.container -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <script src="~/Scripts/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


</body>
</html>

GongchaOfficial/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="~/Content/style/base.css">
    <link rel="stylesheet" href="~/Content/style/header.css">
    <link rel="stylesheet" href="~/Content/style/container.css">
    <link rel="stylesheet" href="~/Content/style/footer.css">

    <script src="~/Content/src/main.js"></script>
    <script src="https://kit.fontawesome.com/0313cd855d.js" crossorigin="anonymous"></script>

    <style>
        * {
            margin: 0;
            text-decoration: none;
            list-style-type: none;
            font-family: "Louis Vuitton Web","Helvetica Neue","Helvetica",Arial,sans-serif;
        }
        body {
            margin: 0;
        }
    </style>
    <title>Gongcha Official</title>

    @*@Scripts.Render("~/bundles/jqueryval")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="app">
        <header class="header">
            <div class="navbar-list">
                <ul class="header__navbar-list-left">
                    <li class="header__navbar-item-left"><a href="">EN</a></li> |
                    <li class="header__navbar-item-left"><a href="">VN</a></li>
                    <li class="header__navbar-item-left"><a href=""><i class="fas fa-map-marker-alt"></i> @Html.ActionLink("Boutiques","Location","Services")</a></li>
                    <li class="header__navbar-item-left"><a href=""><i class="far fa-question-circle"></i> Can we help you?</a></li>
                    <li class="header__navbar-item-left"><a href=""><i class="fas fa-phone"></i> Customer Services</a></li>
                </ul>                
                <ul class="header__navbar-list-right">
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>

            <div class="logo">
                <img src="~/Content/style/img/logo.png" alt="Error">
            </div>

            <div class="gridline">
                <div class="menu">
                    <ul class="header__menu-list">
                        <li id="header__menu-item"><a href="">@Html.ActionLink("Home", "Index", "Home")</a></li>
                        <li id="header__menu-item"><a href="">@Html.ActionLink("Women's Fashion", "Index", "Women")</a></li>
                        <li id="header__menu-item"><a href="">Men's Fashion</a></li>
                        <li id="header__menu-item"><a href="">Collections</a></li>
                        <li id="header__menu-item"><a href="">Make-Up</a></li>
                        <li id="header__menu-item"><a href="">Skincare</a></li>
                        <li id="header__menu-item"><a href="">Services</a></li>
                        <li id="header__menu-item"><i class="fas fa-search"></i> <input type="text" placeholder="Search"></li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="container">
            <div class="grid">

                <div>
                    @RenderBody()
                </div>

            </div>
        </div>

        <footer class="footer">
            <div class="footer__navbar">
                <div class="footer__navbar-top">
                    <ul class="footer_list">
                        <li id="footer-item"><a href="">Gongcha Official</a></li>

                        <li id="footer-item"><a href="">E Center Hutech</a></li>

                        <li id="footer-item"><a href="">Apps</a></li>

                        <li id="footer-item"><a href="">Legal Notices</a></li>

                        <li id="footer-item"><a href="">Contact</a></li>

                        <li id="footer-item"><a href="">Careers</a></li>

                        <li id="footer-item">
                            <a href=""><i class="fab fa-facebook-f">&nbsp;&nbsp;</i></a>
                            <a href=""><i class="fab fa-instagram">&nbsp;&nbsp;</i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer__navbar-bottom">
                    <ul>
                        <li>Copyright <i class="far fa-copyright"></i> 2021 Gongcha Official</li>
                        <li><a href=""><i id="mail-icon" class="fas fa-envelope"></i>&nbsp;service@gongcha.com.vn</a></li>
                        <li>Designed & Developed by: <img src="~/Content/style/img/mysign.png" alt="" style="height: 50px; position: relative;bottom: -19px;"></li>
                    </ul>
                </div>

            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>